FROM python:3.6

WORKDIR /app

#COPY requirements.txt ./

#RUN pip install -r requirements.txt

ARG app_name=projet0
ARG app_port=3000
ARG app_version=1.0
ARG bdd_version=1

COPY database /var/${app_name}/

RUN echo "[DATABASE]\ndirectory = /var/${app_name}/\nversion = ${bdd_version}\n\n[SERVER]\nport = ${app_port}" > config.conf


RUN echo "[DEFAULT]\nconfig_file = config.conf\nrelease = ${app_version}}" > config.ini

COPY server.py .
COPY config.ini .
COPY sql .

EXPOSE ${app_port}

#TODO check config.ini and config.conf

CMD ["python3", "server.py"]