name: Test and push main

on: 
  push:
    branches:
      - main
      - development
  
permissions:
  id-token: write
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Run tests
        run: |
          python3 -m unittest discover -s tests
      - run: pip install ruff
      - run: | 
          ruff check --fix ./api/
      - run: |
          date +%s > run_time
      - name: Push to main if all succesful
        uses: devmasx/merge-branch@master
        with:
          type: now
          target_branch: main
          github_token: ${{ secrets.GITHUB_TOKEN }}
