name: Test and push main

on: 
  push:
    branches:
      - main
      - development
  
permissions:
  id-token: write
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.11]
    env:
      IS_BETA: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Run tests
        run: |
          python3 -m unittest discover -s tests
      - name: Test check
        run: |
          echo ${{ env.IS_BETA }}
      - run: pip install ruff
      - run: | 
          ruff check --fix ./api/

      - name: Push if succesful
        run:
          git config user.name cbilga
          git config user.email cosmin.bilga@gmail.com
          git switch main
          git merge development
          git commit -m "auto merge"
          git push
      #- name: Push to main if all succesful
      #  uses: stefanzweifel/git-auto-commit-action@v5
      #  with:
      #    commit_message: 'Development merge'
      #    tagging_message: 'v1.0.0'
      #    branch: main
