name: Push and test

on: 
  push:
    branches:
      - main
      - development
  
permissions:
  id-token: write
  contents: write


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    env:
      IS_BETA: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
      - name: Run tests
        run: |
          python3 -m unittest discover -s tests
      - name: Test check
        run: |
          echo ${{ env.IS_BETA }}
      - run: pip install ruff
      - run: | 
          ruff check --fix ./api/
      - name: Push to main if all succesful
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Development merge'
          branch: main
